spring:
  application:
    name: online-mall-order
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:152.136.226.157}:${NACOS_PORT:8848}
      username: nacos
      password: nacos
server:
  port: 8083
